### ISSUE TITLE
Requesting update to Readme with a "How to cite" section

### ISSUE THREAD

**Issue by ronniec91** [AMDResearch/omniperf#1]
It would be great to add a `How to cite` section in the README as we expect a lot our out Instinct customers will be keen on using the tool and presenting their results in research papers and conferences. 

This tool will add a tremendous value to our application developers.

**Comment by koomie** [comment]
Thanks for the suggestion. We will look into getting a reference DOI through Zenodo.

**Comment by koomie** [comment]
Going to go ahead and close this out. We have a DOI thru Zenodo now. It is available at: https://doi.org/10.5281/zenodo.7314631.

Associated bibtex entry can be found at: https://zenodo.org/record/7314632/export/hx

We have included pointers to the reference via a badge and text in top-level README.
