### ISSUE TITLE
kernelNames dropdown is unreadable

### ISSUE THREAD

**Issue by coleramos425** [AMDResearch/omniperf#102]
When analyzing a workload in the Flask GUI with very long kernelNames the dropdown filter becomes unreadable. You'll notice text will overlap and it's nearly impossible for the user to work with.

Please fix this menu to account for applications with these longer kernelNames.
![image](https://user-images.githubusercontent.com/11466906/227029018-7d15a0f5-a30f-43d9-848d-34128cadcf93.png)

**Comment by jrmadsen** [comment]
@JoseSantosAMD take a look at these modifications and consider applying them to the causal profiling GUI for omnitrace. I got rid of the basename everywhere bc you ended up with two identical names when two files with the same name but in different directories were added -- so now if you pass the absolute path, the top menu starts to look like this
