### ISSUE TITLE
Request for more succinct L2-per-channel mode

### ISSUE THREAD

**Issue by arghdos** [AMDResearch/omniperf#104]
It's current a bit of a pain to analyze this.  It would be far better (IMO) to have the default channel info be something like:

- min
- max
- mean / median
- std. dev

of each metric, over all 32 channels.  The primary goal of these is to spot imbalances, and that's _easier_ if you get aggregated stats, rather than a list of every value for all M metrics and N channels.  Of course, having the current view as a "--detailed" mode or the like would be nice as well

**Comment by feizheng10** [comment]
Alternatively, we might design like this:
(1) single metric for speed of light: use std.dev across all channels to indict "how imbalance" overall.
(2) box plot per channel shows min/max/mean/median clearly.

**Comment by arghdos** [comment]
I think std. dev. (as a percent of the average) would be a good choice in the SOL

**Comment by coleramos425** [comment]
Added an "Aggregate Stats" table to the top of L2 Cache (per-channel) section. The table contains mean, std dev, min, max.
![image](https://user-images.githubusercontent.com/11466906/230984932-827a7bea-12be-452e-874b-ee19e41823fc.png)

**Comment by coleramos425** [comment]
Feature complete. Feel free to try things out in our `dev` branch ahead of the next release.
