### ISSUE TITLE
Small typo / errors

### ISSUE THREAD

**Issue by arghdos** [AMDResearch/omniperf#107]
https://github.com/AMDResearch/omniperf/blob/9770396fa8d75e2d72ead30890cb9d232ff6ea4a/src/omniperf_analyze/configs/gfx90a/1200_lds.yaml#L25

In ^ (repeated for MI-100/50, etc.) there are two errors:
1. "bandwith" is spelled incorrectly (bandwidth), and
2. This uses a 'L2Banks' parameters which is probably wrong.  On MI-200, the number of L2 channels == the number of LDS banks, but this is not true in general.  This should be a seperate parameter.

@coleramos425  bug me and I can get you the right values for L2 channels / LDS banks, etc.

**Comment by coleramos425** [comment]
Updated. Thanks Nick.
