### ISSUE TITLE
omniperf profile python workload is throwing error

### ISSUE THREAD

**Issue by jin-xu-amd** [AMDResearch/omniperf#108]
This is the command i use to profile my small python workload. 
omniperf profile -n optimizer  -- python simple_NN.py

But i am getting following error message. 
**usage: omniperf [mode] [options]
tool: error: Your command "python" doesn't point to a file. Try again.**

Can you please help? why profiler doesn't work on python code?

**Comment by jin-xu-amd** [comment]
Thanks for the quick response! 
Now, it is giving an error on the second line.
    **import torch
ModuleNotFoundError: No module named 'torch'**

I am running the workload in pytorch docker, so i am not sure why it is still complaining torch not found.
Also, just give a quick background, I was able to run the same code using MLPerf_CLI(link below) without any issue.
https://confluence.amd.com/display/MLSE/Omniperf%28MIPerf%29+CLI+analysis
But I was told MIPerf_CLI is deprecated and the omniperf is more up-to-date with bug fixes, so i am planning to use this instead.
Thanks!

**Comment by jrmadsen** [comment]
Try using `#!/usr/bin/env python3` instead. If your pytorch install is not in `/usr/bin/python3` it is picking up the wrong Python installation

**Comment by jin-xu-amd** [comment]
Thanks! This is working! :-)
