### ISSUE TITLE
Is it possible to create random http port number when using --gui?

### ISSUE THREAD

**Issue by gmarkomanolis** [AMDResearch/omniperf#111]
Could we have a random port generator when we use --gui so someone could not know the port and access another person's data if they share a server?

**Comment by coleramos425** [comment]
We could add a `--random-port` option that generates a random number in the Registered Ports range (1024-49151)

The chosen random port would override the default GUI port.

**Comment by coleramos425** [comment]
Feature complete. Feel free to try things out in our `dev` branch ahead of the next release,
