### ISSUE TITLE
--kernel-names support for longer names or at least print the first X characters

### ISSUE THREAD

**Issue by gmarkomanolis** [AMDResearch/omniperf#115]
Hi, the kernel names legend hides some names of kernel, could we extend it to support longer names or something else?

[kernelName_legend.pdf](https://github.com/AMDResearch/omniperf/files/11262470/kernelName_legend.pdf)

**Comment by coleramos425** [comment]
Thanks for pointing this out @gmarkomanolis. Adding feature to TODO for next release
