### ISSUE TITLE
AAC Requirements

### ISSUE THREAD

**Issue by coleramos425** [AMDResearch/omniperf#12]
1. ~~Need instruction to install docker-compose and volumes~~ (added in v1.0.3)
2. Need to install CMake 3.19 separately
3. Modify Python dependency instructions to `python3 -m pip install **--system** -t ${INSTALL_DIR}/python-libs -r requirements.txt`
4. We see matplotlib conflict with the default installation, resulting in omniperf failure
5. AAC default is ubuntu18.04/python3.6.9, while we require u20.04/py3.7+. might be helpful, after testing, relax the constraints
6. Add `sudo apt install libjpeg-dev zlib1g-dev` to install instuctions. This is required by Pillow

cc: Xiaomin Lu

**Comment by koomie** [comment]
Regarding the `cmake` comment, that is already called out as a basic dependency requirement already in the docs. Were you wanting something more than that? Documenting how to install would be OS and system dependent (rhel/ubuntu/sles, etc and most production HPC sites will have a cmake module available).  Similarly, we probably don't want to go down the road of talking about the myriad of ways to install python.

**Comment by koomie** [comment]
I have access to this system now and will do some testing...

**Comment by coleramos425** [comment]
ACC instance has been configured for Omniperf (thanks @koomie). Closing issue.
