### ISSUE TITLE
Units missing from L2 per-channel breakdown

### ISSUE THREAD

**Issue by arghdos** [AMDResearch/omniperf#133]
![image](https://github.com/AMDResearch/omniperf/assets/6463881/7e6c8086-d25a-4837-9f79-8d2c5af11b6d)

I think we just have to copy the units from the base metric into, e.g.:

https://github.com/AMDResearch/omniperf/blob/8af6efc0be5288dadd2e758556154e52f7406e5d/src/omniperf_analyze/configs/gfx90a/1800_L2_cache_per_channel.yaml#L207

**Comment by coleramos425** [comment]
Could you elaborate @arghdos. Per your screenshot, I'm reading metrics 18.1.1 - 18.1.7 all as "...req per $normUnit". Which seems correct to me

Am I missing something?

**Comment by coleramos425** [comment]
Patch merged into `dev`. Closing issue.
