### ISSUE TITLE
The kernel filtering example should give some level of detail on how the filter is used

### ISSUE THREAD

**Issue by arghdos** [AMDResearch/omniperf#136]
https://github.com/AMDResearch/omniperf/blob/a346db7646b0a935f4cac51d131b4a585f065c05/src/docs/profiling.md?plain=1#L283

Currently we just say "it's compatible with rocprof".  It would be more accurate (to my understanding) to say that it is a regular expression that used to match against the demangled kernel name.

**Comment by coleramos425** [comment]
Done. Revisiting that section, it's clear more specificity was needed. Thanks
