### ISSUE TITLE
Add % of peak values to block-level speed-of-light charts

### ISSUE THREAD

**Issue by arghdos** [AMDResearch/omniperf#140]
This was brought up in a demo today.  Would improve consistency.

**Comment by JoseSantosAMD** [comment]
@arghdos Added percent to the units in the CLI charts to be more consistent with the % units in the Speed-of-Light charts in the GUI. Is this what you meant?

**Comment by arghdos** [comment]
... sort of, the original ask was to add a % of Peak to appropriate metrics inside of the block-level SOL tables, so e.g., the Instruction Cache bandwidth as a percent of theoretically achievable peak.  Your PR is a decent start, but I'm a bit wary of some of these, e.g.:

![image](https://github.com/AMDResearch/omniperf/assets/6463881/c1985484-18e6-4693-90b6-1075ccb5b7e9)

_appears_ to be in % of Peak form (I haven't specifically verified it), but isn't labeled as such

**Comment by JoseSantosAMD** [comment]
![image](https://github.com/AMDResearch/omniperf/assets/87447437/76306878-4bb1-4ab3-ad2a-d11fb82fdedc)
Like this?

**Comment by coleramos425** [comment]
Implemented. Thanks for closing this, Jose
