### ISSUE TITLE
Support for Ubuntu 22.04

### ISSUE THREAD

**Issue by akadutta** [AMDResearch/omniperf#143]
This is a request to add support for Ubuntu 22.04.

**Comment by coleramos425** [comment]
Specifically, we'll need to add a roofline binary here
https://github.com/AMDResearch/omniperf/blob/435aa2b073eb3c93b3663f8e35c09b70d5465f81/src/omniperf#L302-L329

@JoseSantosAMD can you see about adding this and submitting a PR against `dev` branch. If you need an Ubuntu 22.04 machine to test this let me know. I'd recommend a docker container

**Comment by coleramos425** [comment]
Fixed here: https://github.com/AMDResearch/omniperf/commit/17422b056ae2e184424aa1991c7528ff8e106017

This will be available in v2.0.0 (eta 3/15/24).
