### ISSUE TITLE
GDS column under instruction mix on web GUI is incorrect.

### ISSUE THREAD

**Issue by hsadasiv** [AMDResearch/omniperf#150]
Omniperf v1.0.8 on gfx90a.
I'm seeing the GDS instructions under instruction mix is reported zero when I can correctly spot the atomics in the L2 cache.

**Comment by coleramos425** [comment]
@hsadasiv what atomics in particular indicate a discrepancy between the two measures? Can you please attach screenshots of the Omniperf metrics you're referencing to reach this conclusion? Thanks

**Comment by arghdos** [comment]
GDS is always expected to be zero, as it is typically unused.  Feel free to reach out internally to discuss further.

**Comment by coleramos425** [comment]
Closing ticket. Please reopen if additional clarification is required.
