### ISSUE TITLE
None of instruction mix panels contain min/max/avg breakdown across dispatches

### ISSUE THREAD

**Issue by arghdos** [AMDResearch/omniperf#154]
E.g.,:

https://github.com/AMDResearch/omniperf/blob/6487ba3853deaf97a91e03c0dc4d8a8109099546/src/omniperf_analyze/configs/gfx90a/1000_compute-unit-instruction-mix.yaml#L24

![image](https://github.com/AMDResearch/omniperf/assets/6463881/5cf5b802-cf3d-41e4-85b6-99b3a5df8a9e)

This is just implicitly giving you an average over all selected dispatches, which is pretty different from all the other tables.

**Comment by arghdos** [comment]
Same issue exists for the compute pipeline SOL:

https://github.com/AMDResearch/omniperf/blob/ed31b8a988b0fde6a5e11bc949417c82c6db1abc/src/omniperf_analyze/configs/gfx90a/1100_compute-unit-compute-pipeline.yaml#L20

**Comment by coleramos425** [comment]
Implemented
