### ISSUE TITLE
Output data format

### ISSUE THREAD

**Issue by ooreilly** [AMDResearch/omniperf#17]
```
omniperf -v
omniperf (1.0.3)

omniperf analyze -p workloads/kernel/mi200/ -o doesnotexist

--------
Analyze
--------

Saved Analysis folder exists
```
Why does `omniperf analysis` say: `Saved Analysis folder exists` ? The folder does not exist. If create the directory and rerun, I get:
```
IsADirectoryError: [Errno 21] Is a directory: 'doesnotexist'
```
I guess that `omniperf` says `Saved analysis folder exists` because I pointed it to the existing workload `workloads/kernel/mi200`. 

The output that I get via `-o` is the stdout? It would be helpful it the data was in say sqlite, json, or even Python pickle file. Such an option would facilitate further analysis.

**Comment by coleramos425** [comment]
The "Saved Analysis folder exists" is verbose output from Omniperf indicating that its sucessfully detected some results that we've cached in your workloads folder. For example

**Comment by coleramos425** [comment]
@ooreilly let me know if you have any follow-up questions or comments. Otherwise, I'll mark this issue as closed. Thanks!

**Comment by ooreilly** [comment]
@coleramos425 Thanks for the clarifications. I think it could be enabled when pass -V. I don't see have that information is useful in general. Can you perform an analysis without having a saved folder? 

You can close this ticket, and I will open a feature request for saving the output data in different formats.
