### ISSUE TITLE
Inconsistent use of "mean" vs "average"

### ISSUE THREAD

**Issue by arghdos** [AMDResearch/omniperf#184]
**Describe the bug**

Not a huge issue, but I've noticed we interchangeably use mean vs avg in the yaml defintions:

https://github.com/search?q=repo%3AAMDResearch%2Fomniperf+mean+path%3A**%2F*.yaml&type=code
https://github.com/search?q=repo%3AAMDResearch%2Fomniperf+avg%3A+path%3A**%2F*.yaml&type=code

It would be good to just choose one and be consistent (I have no preference)

**Comment by coleramos425** [comment]
Thanks. This was addressed in commit https://github.com/AMDResearch/omniperf/commit/8936966e81a3c7ac3b2697e3f98fa539129b6d90. Things are up-to-date in the `dev` branch

**Comment by arghdos** [comment]
Ahh, thanks -- was looking at the wrong branch :)
