### ISSUE TITLE
Roofline Support for RHEL9

### ISSUE THREAD

**Issue by JoseSantosAMD** [AMDResearch/omniperf#188]
**Describe the bug**
Omniperf says that roofline is not supported in Platform:el9. After further investigation, I see it checks for Platform:el8 because that is the os that omniperf has a roofline binary for.

**Development Environment:**
 - Linux Distribution: RHEL9
 - Omniperf Version: 1.0.10
 - GPU: mi200
 - Custer (if applicable): HPCFund

**To Reproduce**
1. Run omniperf profile -n app --path workload -- ./sample/vcopy 1048576 256

**Expected behavior**
I Expected omniperf to profile application with roofline

**Screenshots**
![image](https://github.com/AMDResearch/omniperf/assets/87447437/8752df22-ca75-4938-b9e5-8619ad1a260e)

**Comment by coleramos425** [comment]
@JoseSantosAMD if you have any spare cycles see if you can take a look at this. It should be an easy fix. We'll just need to update this area of the code:

https://github.com/AMDResearch/omniperf/blob/235f812e2cdbc5b751b5e961da15397938771d08/src/omniperf#L293-L329

This can be added to the `2.x` branch.

**Comment by coleramos425** [comment]
Patched in the above PR.
