### ISSUE TITLE
Change "IP Block" to "Hardware Block" in help menu

### ISSUE THREAD

**Issue by coleramos425** [AMDResearch/omniperf#201]
**Is your feature request related to a problem? Please describe.**
Per the Omniperf documentation overhaul, we've agreed to change references to the term "IP Block" to "Hardware Block" for clarity. 

**Describe the solution you'd like**
Change instances of "IP Block" to "Hardware Block", i.e.,
https://github.com/AMDResearch/omniperf/blob/b9e474ec5ff6afcb3ebafc653dcb475acd7096d0/src/parser.py#L164-L174

https://github.com/AMDResearch/omniperf/blob/b9e474ec5ff6afcb3ebafc653dcb475acd7096d0/src/parser.py#L413-L420

CC: @gsitaram

**Comment by gsitaram** [comment]
@coleramos425 , thanks for copying me. I'll modify the documentation accordingly.

**Comment by coleramos425** [comment]
Complete and targeted for v2.0.0
