### ISSUE TITLE
list-metrics without a path returns an error

### ISSUE THREAD

**Issue by JoseSantosAMD** [AMDResearch/omniperf#219]
**Describe the bug**

**Development Environment:**
 - Linux Distribution: Ubuntu20.04
 - Omniperf Version: 1.0.10
 - GPU: [e.g. Mi100, Mi200]

**To Reproduce**
1. Run omniperf analyze --list-metrics gfx908
2. See error 
File "/home/jose/omniperf/src/omniperf_analyze/analysis_base.py", line 151, in sanitize
    for dir in self.__args.path:
TypeError: 'NoneType' object is not iterable

**Expected behavior**
architecture metrics to be listed

**Screenshots**
<img width="475" alt="image" src="https://github.com/AMDResearch/omniperf/assets/87447437/be583b7e-cdec-4a2f-ac6a-0397e5cddf34">

**Comment by coleramos425** [comment]
Patched. `--list-metrics` will now require a path because its implementation now peaks memory partitioning info from sys_info.csv. Updated code to catch this gracefully and throw a helpful error.
