### ISSUE TITLE
Have CI build docs in lieu of current update-docs.sh script

### ISSUE THREAD

**Issue by koomie** [AMDResearch/omniperf#22]
Would be nice to clean up the docs build a bit and have a companion github action land html from markdown.  Also, I'd be in favor of cleaning up the branches so that all docs collateral only resides in the `gh-pages` branch. In that case we would remove from `main` and `dev`.

**Comment by jrmadsen** [comment]
I prefer the markdown source to be part of the repo. It allows you to update/modify the docs alongside changes in the source (same PR) and can also help while searching for things in repo

**Comment by arghdos** [comment]
Also, turn warnings as errors on (if possible) for things like #33

**Comment by koomie** [comment]
This is now live with the introduction of a new github action: [docs.yml](.github/workflows/docs.yml)

In the current configuration, the authoritative markdown inputs live in `src/docs` on the **main** branch.  When documentation-related changes occur on the main branch, a CI job will build the latest docs using a sphinx container. These are then deployed to GitHub pages using the [deploy-pages](https://github.com/actions/deploy-pages) action.

Note that with this approach, static html files no longer need to reside in the repository.
