### ISSUE TITLE
No GFX942 in --list-metrics

### ISSUE THREAD

**Issue by Lynd98** [AMDResearch/omniperf#229]
lstringe@pp-128-b1-2:~/618StandAlone/workloads/618/MI300A_A1$ **omniperf analyze --list-metrics gfx942**
usage:
omniperf analyze --path <workload_path> [analyze options]

-------------------------------------------------------------------------------

Examples:

        omniperf analyze -p workloads/vcopy/mi200/ --list-metrics gfx90a

        omniperf analyze -p workloads/mixbench/mi200/ --filter-dispatch-ids 12 34 --decimal 3

        omniperf analyze -p workloads/mixbench/mi200/ --gui

-------------------------------------------------------------------------------

**tool: error: argument --list-metrics: invalid choice: 'gfx942' (choose from 'gfx906', 'gfx908', 'gfx90a')**

**Development Environment:**
 - Linux Distribution: 5.18.2-mi300-build-140423-ubuntu-22.04+
 - Omniperf Version: 
 - ----------------------------------------
Omniperf version: 1.1.0-PR1 (release)
Git revision:     6d072ac
----------------------------------------
 - GPU: MI300A
 - Custer: Parry Peak

**To Reproduce**
1. Run: omniperf analyze --list-metrics gfx942
2. See error

**Expected behavior**
List the gfx942 metrics

**Comment by Lynd98** [comment]
Here is how I build Omniperf.

lstringe@pp-128-b1-2:~/Omniperf$ cat DoIt.sh
# Build Omniperf

cd /home/lstringe/Omniperf
rm -rf omniperf-1.1.0-PR1
rm -rf omniperf

git clone https://github.com/AMDResearch/omniperf.git
cd omniperf
git checkout mi300
export INSTALL_DIR=/home/lstringe/Omniperf/omniperf
python3 -m pip install -t ${INSTALL_DIR}/python-libs -r requirements.txt
mkdir build
cd build
cmake -DCMAKE_INSTALL_PREFIX=${INSTALL_DIR}/1.1.0-PR1 -DPYTHON_DEPS=${INSTALL_DIR}/python-libs -DMOD_INSTALL_PATH=${INSTALL_DIR}/modulefiles ..
make install
cd ..
find . -name omniperf

export AOMP=/COD/2024-01-08/aomp
export PATH=$AOMP/bin:$PATH
export LD_LIBRARY_PATH=$AOMP/lib:$LD_LIBRARY_PATH
export PATH=/home/lstringe/Omniperf/omniperf/1.1.0-PR1/bin:$PATH

**Comment by coleramos425** [comment]
Issue patched here:
https://github.com/AMDResearch/omniperf/commit/475515ebe77389148fdb463ccec135991565ed49

Thanks for reporting issue. Please re-try.
