### ISSUE TITLE
omniperf analyze KeyError: 'gpu-id' with a gfx942 workload

### ISSUE THREAD

**Issue by Lynd98** [AMDResearch/omniperf#230]
**Describe the bug**
lstringe@pp-128-b1-2:~/618StandAlone$ omniperf analyze --path ./workloads/618/MI300A_A1 --gui

--------
Analyze
--------

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/pandas/core/indexes/base.py", line 3790, in get_loc
    return self._engine.get_loc(casted_key)
  File "index.pyx", line 152, in pandas._libs.index.IndexEngine.get_loc
  File "index.pyx", line 181, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 7080, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 7088, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'gpu-id'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/lstringe/Omniperf/omniperf/1.1.0-PR1/bin/omniperf", line 970, in <module>
    main()
  File "/home/lstringe/Omniperf/omniperf/1.1.0-PR1/bin/omniperf", line 950, in main
    analyze(args)
  File "/home/lstringe/Omniperf/omniperf/1.1.0-PR1/bin/omniperf_analyze/omniperf_analyze.py", line 332, in analyze
    run_gui(args, runs)
  File "/home/lstringe/Omniperf/omniperf/1.1.0-PR1/bin/omniperf_analyze/omniperf_analyze.py", line 205, in run_gui
    gui.build_layout(
  File "/home/lstringe/Omniperf/omniperf/1.1.0-PR1/bin/omniperf_analyze/utils/gui.py", line 436, in build_layout
    get_header(base_data.raw_pmc, input_filters, filt_kernel_names),
  File "/home/lstringe/Omniperf/omniperf/1.1.0-PR1/bin/omniperf_analyze/utils/gui_components/header.py", line 187, in get_header
    raw_pmc[
  File "/usr/local/lib/python3.10/dist-packages/pandas/core/frame.py", line 3896, in __getitem__
    indexer = self.columns.get_loc(key)
  File "/usr/local/lib/python3.10/dist-packages/pandas/core/indexes/base.py", line 3797, in get_loc
    raise KeyError(key) from err
KeyError: 'gpu-id'

**Development Environment:**
 - Linux Distribution: 5.18.2-mi300-build-140423-ubuntu-22.04+
 - Omniperf Version: 
 - ----------------------------------------
Omniperf version: 1.1.0-PR1 (release)
Git revision:     6d072ac
----------------------------------------

 - GPU: MI300A
 - Custer: Parry Peak

**To Reproduce**
1. Run 
// To compile //
lstringe@pp-128-b1-2:~/618StandAlone$ cat DoIt.sh
#!/bin/bash

export AOMP=/COD/LATEST/aomp
export PATH=$AOMP/bin:$PATH
export LD_LIBRARY_PATH=$AOMP/lib:$LD_LIBRARY_PATH

ulimit -s unlimited
export OMP_TARGET_OFFLOAD=MANDATORY
export LIBOMPTARGET_KERNEL_TRACE=1
export ROCR_VISIBLE_DEVICES=0
export GOMP_CPU_AFFINITY=1-7:1

echo;echo "618.tealeaf major loop";echo
rm Loop1
which clang
# export CCC_OVERRIDE_OPTIONS"+-fopenmp-force-usm"
clang -O3 -g -ggdb -fopenmp-target-fast -fopenmp-target-xteam-reduction-blocksize=64 -fopenmp --offload-arch=gfx942 calc_ur.c -o Loop1

# HSA_XNACK=1 rocprof --stats ./Loop1
HSA_XNACK=1 ./Loop1

// To Run Omniperf //
lstringe@pp-128-b1-2:~/618StandAlone$ cat RunOmniperf.sh
export ROCPROF=/COD/2024-01-18/aomp_18.0-2/bin/rocprofv2
omniperf profile -n 618 -- ./Loop1

4. To create the error:
omniperf analyze --path ./workloads/618/MI300A_A1 --gui

6. See error

**Expected behavior**
A GUI should appear.

**Screenshots**

**Additional context**
// Here is the source code. //

lstringe@pp-128-b1-2:~/618StandAlone$ cat calc_ur.c
// 618.tealeaf_t/build/build_base_clang_omp_target_gfx90a.0000/2d/c_kernels/cg.c
// cg_calc_ur line 184

#include <stdio.h>
#include <stdarg.h>
#include <stdlib.h>
#include <omp.h>

int main(int argc, char** argv)
{

   double* rrn;
   double* u;
   double* p;
   double* r;
   double* w;

   int halo_depth = 2;
   int x = 16388;
   int y = 16388;
   double alpha = 0.000005;
   int xy = x*y;
   double rrn_temp = 0.0;

    u  = (double*)malloc(sizeof(double)*x*y);
    p  = (double*)malloc(sizeof(double)*x*y);
    r  = (double*)malloc(sizeof(double)*x*y);
    w  = (double*)malloc(sizeof(double)*x*y);

    srand(123456789);
    for(int jj = 0; jj < y; ++jj) {
        for(int kk = 0; kk < x; ++kk) {
            const int index = kk + jj*x;
            u [index] = (double)rand()/RAND_MAX;
            p [index] = (double)rand()/RAND_MAX;
            r[index] = (double)rand()/RAND_MAX;
            w[index] = (double)rand()/RAND_MAX;
        }
    }

   for (int i=0; i<5; i++) {
      double t0 = omp_get_wtime();

      #pragma omp target teams distribute parallel for simd map(tofrom:rrn_temp) reduction(+:rrn_temp) collapse(2) map(tofrom: u[:xy], p[:xy], w[:xy], r[:xy])
      for(int jj = halo_depth; jj < y-halo_depth; ++jj) {
         for(int kk = halo_depth; kk < x-halo_depth; ++kk) {
            const int index = kk + jj*x;

            u[index] += alpha*p[index];
            r[index] -= alpha*w[index];
            rrn_temp += r[index]*r[index];
         }
      }
      double elapsed = omp_get_wtime() - t0;
      printf ("elapsed = %E\n", elapsed);
      printf ("rrn_temp = %E\n",rrn_temp);
      printf ("w,p=%E, %E\n\n",w[0],p[0]);
   }
}

**Comment by Lynd98** [comment]
Here is how I built Omniperf.

lstringe@pp-128-b1-2:~/Omniperf$ cat DoIt.sh
# Build Omniperf

cd /home/lstringe/Omniperf
rm -rf omniperf-1.1.0-PR1
rm -rf omniperf

git clone https://github.com/AMDResearch/omniperf.git
cd omniperf
git checkout mi300
export INSTALL_DIR=/home/lstringe/Omniperf/omniperf
python3 -m pip install -t ${INSTALL_DIR}/python-libs -r requirements.txt
mkdir build
cd build
cmake -DCMAKE_INSTALL_PREFIX=${INSTALL_DIR}/1.1.0-PR1 -DPYTHON_DEPS=${INSTALL_DIR}/python-libs -DMOD_INSTALL_PATH=${INSTALL_DIR}/modulefiles ..
make install
cd ..
find . -name omniperf

export AOMP=/COD/2024-01-08/aomp
export PATH=$AOMP/bin:$PATH
export LD_LIBRARY_PATH=$AOMP/lib:$LD_LIBRARY_PATH
export PATH=/home/lstringe/Omniperf/omniperf/1.1.0-PR1/bin:$PATH

**Comment by coleramos425** [comment]
The issue has been patched here: 
https://github.com/AMDResearch/omniperf/commit/e62019d03515dfb7db937581580a6f99fcf57372

Thanks for the detailed reproducer. Please try again.
