### ISSUE TITLE
Support dispatch listing in Omniperf analyze mode

### ISSUE THREAD

**Issue by amnamasood-amd** [AMDResearch/omniperf#237]
I would like to request a feature to support listing of all the kernel dispatches, along with their kernel names and timing information. Some additional features would be the ability to filter the dispatches by kernel names and sorting them according to the time taken for the dispatch to complete. These features are supported in Grafana GUI but not in the CLI mode.

**Comment by coleramos425** [comment]
Added here: 
https://github.com/AMDResearch/omniperf/commit/bd83f68412fcb27455718999ccfe5c18faa332b9

This is slated to be included in the next release. Here's a screengrab to preview functionality:
![image](https://github.com/AMDResearch/omniperf/assets/11466906/4cecee22-2a62-473a-b821-625f65f62024)
