### ISSUE TITLE
Python error when running omniperf profile (UnicodeDecodeError)

### ISSUE THREAD

**Issue by benrichard-amd** [AMDResearch/omniperf#250]
**Describe the bug**
`omniperf profile` crashes with Python error: `UnicodeDecodeError`

**Development Environment:**
 - Linux Distribution: Both `Ubuntu 20.04` and `Ubuntu 22.04`
 - Omniperf Version: `1.1.0-PR1 (release)`  Git revision:     b9e474e
 - GPU: `MI200`

**To Reproduce**

Run `omniperf profile`, for example:

`omniperf profile --name gemm_test -- ./gemm`

Output:
```
Resolving rocprof
ROC Profiler:  /opt/rocm-6.0.0/bin/rocprof
Traceback (most recent call last):
  File "./omniperf/bin/omniperf", line 889, in <module>
    main()
  File "./omniperf/bin/omniperf", line 738, in main
    args.target = get_soc()
  File "./omniperf/bin/omniperf", line 109, in get_soc
    mspec = specs.get_machine_specs(0)
  File "/home/user/omniperf/bin/utils/specs.py", line 220, in get_machine_specs
    rocm_smi = run(["rocm-smi"])
  File "/home/user/omniperf/bin/utils/specs.py", line 154, in run
    return p.stdout.decode("ascii")
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc2 in position 599: ordinal not in range(128)
```
**Expected behavior**
Profiling happens successfully

**Additional context**
Changing `"ascii"` to `"utf-8"` on that line seems to avoid the issue.

**Comment by coleramos425** [comment]
Thanks for the report @benrichard-amd . The issue has been patched (here https://github.com/AMDResearch/omniperf/commit/d9a6832e3063c61f8866d380546a82fe8fe7914f ) and will be included in the upcoming release.
