### ISSUE TITLE
max_mclk --showmclkrange error Mi100

### ISSUE THREAD

**Issue by JoseSantosAMD** [AMDResearch/omniperf#254]
**Describe the bug**
After testing latest 2.x I found that max_mclk is populated as None. Leading to errors in later Omniperf profiling pipeline. Seems to be coming from #243 

https://github.com/AMDResearch/omniperf/blob/852cc13f2a8057710f456bdbe567643831fc701d/src/utils/specs.py#L136-L138

I tested `--showmclkrange` on several MI100 systems and it appears that this value will always be None.

**Development Environment:**
 - Linux Distribution: RHEL8
 - Omniperf Version: Latest 2.x
 - GPU: Mi100
 - Custer : HPCFund, Thera

**To Reproduce**
1. Run `omniperf profile -n vcopy --./tests/vcopy 1048576 256`

**Screenshots**
![MicrosoftTeams-image (4)](https://github.com/AMDResearch/omniperf/assets/87447437/acf2a715-979a-48ec-a05e-1f0488f3a6ee)

**Comment by coleramos425** [comment]
Thanks Jose. I was able to reproduce this error as well. Adding @skyreflectedinmirrors who may know more about why we're seeing this.

**Comment by skyreflectedinmirrors** [comment]
Sigh, yeah -- looking into this it seems like a limitation of SMI on MI100.  I'll code in a workaround.

**Comment by skyreflectedinmirrors** [comment]
@JoseSantosAMD -- can you try: https://github.com/AMDResearch/omniperf/pull/256

**Comment by koomie** [comment]
Resolved now in CI via #256.  Thanks.
