### ISSUE TITLE
Syntax error when giving the same path twice to CLI Baseline

### ISSUE THREAD

**Issue by JoseSantosAMD** [AMDResearch/omniperf#260]
**Describe the bug**
I get the following error when I pass the same path to baseline
SyntaxError: (unicode error) 'utf-8' codec can't decode byte 0x9a in position 0: invalid start byte

**Development Environment:**
 -RHEL8
 - lates 2.x
 - Mi100, Mi200
 - Custer (if applicable): HPCFund

**To Reproduce**
1. Run ./src/omniperf analyze --path tests/workloads/vcopy/MI200 --path tests/workloads/vcopy/MI200
2. See error
<img width="674" alt="image" src="https://github.com/AMDResearch/omniperf/assets/87447437/0ffdad36-803c-4f07-9f95-ee2d7edbdd97">

**Comment by coleramos425** [comment]
Related to #67

**Comment by coleramos425** [comment]
Resolved
