### ISSUE TITLE
Seems finding invalid Kernel id is off by one

### ISSUE THREAD

**Issue by JoseSantosAMD** [AMDResearch/omniperf#261]
**Describe the bug**
Seems finding invalid Kernel id is off by one

**Development Environment:**
 - Linux Distribution: RHEL8
 - Omniperf Version: latest 2.x
 - GPU: Mi100, Mi200
 - Custer (if applicable): HPCFund

**To Reproduce**
1. Run ./src/omniperf analyze --path tests/workloads/vcopy/MI200/ -k 1
2. See Error
<img width="530" alt="image" src="https://github.com/AMDResearch/omniperf/assets/87447437/b60db3a8-a27f-47a1-8c13-2a8127aafa35">

**Expected behavior**
[ERROR]: 1 is an invalid kernel id. Please enter an id between 0-1
.

**Comment by coleramos425** [comment]
See https://github.com/AMDResearch/omniperf/pull/287#issuecomment-1971719951

**Comment by coleramos425** [comment]
Implemented
