### ISSUE TITLE
Hard coded bandwidth in standalone GUI ranges

### ISSUE THREAD

**Issue by skyreflectedinmirrors** [AMDResearch/omniperf#282]
https://github.com/AMDResearch/omniperf/blob/b9e474ec5ff6afcb3ebafc653dcb475acd7096d0/src/omniperf_analyze/utils/gui.py#L249

Probably just need to pipe the machine specs down into there, so we can read the field directly.

**Comment by coleramos425** [comment]
Closed in #302
