### ISSUE TITLE
Write statistics does not match understanding

### ISSUE THREAD

**Issue by mzi214** [AMDResearch/omniperf#29]
Hi, We are running an all-reduce kernel (with remote memory stores) on 4 MI210s and are trying to understand the memory traffic using MIPERF (snapshot for one is attached). We are unclear about what each of the Writes are counting and had the following questions we were hoping you could help with: 

i) We find that the ‘Write (64B)’ is the sum of ‘Write (Uncached 32B)’ and  ‘HBM Write’ (minus the ‘Write (32B)’, which is small anyway). 
      - Why are 32B writes (Writes (Uncached 32B)) being counted as 64B writes (Write (64B))? Are the ‘Writes (Uncached 32B)’ actually 64B 
      - Are ‘HBM write’ also 64B writes?
ii) Should we use ‘HBM writes’ and the ‘Write (Uncached 32B)’ separately as 64B and 32B writes, instead of the considering the combined ‘Write (64B)’?

Thank you!
![write_stat](https://user-images.githubusercontent.com/113731661/201825357-f830bb9e-31f3-4390-b7cc-6ed8875cd9ab.png)

**Comment by arghdos** [comment]
I'm working on documentation that will hopefully explain this better, but I'm not out to the L2/EA yet (still in L1).  Will keep you updated @mzi214

**Comment by mzi214** [comment]
Thanks for  your feedback @arghdos, sure I will wait till you reach there.
