### ISSUE TITLE
Dead link to grafana in getting started

### ISSUE THREAD

**Issue by arghdos** [AMDResearch/omniperf#33]
https://github.com/AMDResearch/omniperf/blob/5fa2dd99bc0d4491750d9287ca6e854bf5fe7770/src/docs/getting_started.md?plain=1#L72

Now that grafana-analysis has it's own page, this link needs to be updated

**Comment by koomie** [comment]
Oopsie - that is almost certainly my fault. I'll update the link.

**Comment by koomie** [comment]
Fix should be live now, but follow-up if something still looks amiss.
