### ISSUE TITLE
Ubuntu 20_04 roofline not installed

### ISSUE THREAD

**Issue by aosewski** [AMDResearch/omniperf#34]
I just found that the roofline analysis file for Ubuntu 20_04 is not installed. Take a look here: https://github.com/AMDResearch/omniperf/blob/main/CMakeLists.txt#L227-L229

**Comment by coleramos425** [comment]
Thanks for pointing this out. We'll get that added

**Comment by coleramos425** [comment]
We've added a patch to our `dev` branch. Expect this to be rolled out in v1.0.5 of Omniperf

Let us know if you encounter any other issues.
