### ISSUE TITLE
Update L1 bandwidth metric calculations

### ISSUE THREAD

**Issue by arghdos** [AMDResearch/omniperf#36]
For the L1 bandwidth calcs in the SoL section, we should be using:

`64 * tcp_total_cache_accesses_sum / Duration`

This will need to be changed in both the yaml configs (for CLI / standalone), e.g.:

https://github.com/AMDResearch/omniperf/blob/main/src/omniperf_cli/configs/gfx90a/1600_L1_cache.yaml#L28

and the grafana dashboard (`cacheBW_pct` in the vL1 data section)

**Comment by coleramos425** [comment]
Updated metrics in Grafana and config files. 

`64 * tcp_total_cache_accesses_sum / Duration` yields a GB/s format. I tweaked the equation slightly to reflect Pct-of-Peak measure i.e. 

`((100 * AVG(((TCP_TOTAL_CACHE_ACCESSES_sum * 64) / (EndNs - BeginNs))))
              / ((($sclk / 1000) * 64) * $numCU))`

**Comment by arghdos** [comment]
Any particular reason why we'd want it as a PoP?  If you look at e.g., the L2<->EA bandwidths, they're reported as raw BWs:

```
AVG((((TCC_EA_RDREQ_32B_sum * 32) + ((TCC_EA_RDREQ_sum - TCC_EA_RDREQ_32B_sum)
              * 64)) / (EndNs - BeginNs)))
```

IMO, the PoP is more appropriate for the top-level speed-of-light chart (which I just checked, actually used the new definition :P)

**Comment by coleramos425** [comment]
We've decided to leave the _Pct-of-Peek metric_ in our **SOL** section (since it's a more contextualized measurement) and add a _raw BW metric_ to the **L1D Cache Accesses** section.

Closing issue.
