### ISSUE TITLE
Add L1<->L2 bandwidth calculation

### ISSUE THREAD

**Issue by arghdos** [AMDResearch/omniperf#37]
Omniperf currently does not report the achieved L2 bandwidth from the L1s, despite collecting the counters required to do so.
Following the convention for L1 bandwidth calculations, this is essentially the total amount of data moved from L1<->L2, which can be calculated from the L1<->L2 requests, e.g.: 

https://github.com/AMDResearch/omniperf/blob/main/src/omniperf_cli/configs/gfx90a/1600_L1_cache.yaml#L173

The L2 bandwidth calculation would be:

```
L2 BW = 64B * (TCP_TCC_READ_REQ_sum + TCP_TCC_WRITE_REQ_sum + TCP_TCC_ATOMIC_WITH_RET_REQ_sum + TCP_TCC_ATOMIC_WITHOUT_RET_REQ_sum) / $denom
```

**Comment by arghdos** [comment]
It was pointed out that L1<->L2 bandwidth is a better naming scheme for this, as this excludes instruction cache and scalar cache traffic.

**Comment by coleramos425** [comment]
Is **L1D Cache Accesses** panel the only place we want to add this @arghdos ? To summarize, I:

1. Changed name of `L1-TCR` -> `L1-TCC`
2. Added `L1-L2 BW` using:
```
L1_L2_BW = 64B * (TCP_TCC_READ_REQ_sum + TCP_TCC_WRITE_REQ_sum + TCP_TCC_ATOMIC_WITH_RET_REQ_sum + TCP_TCC_ATOMIC_WITHOUT_RET_REQ_sum) / $denom
```

Before:
![image](https://user-images.githubusercontent.com/11466906/205990813-e831cd93-f41d-49a0-af8a-284477ce167a.png)

After:
![image](https://user-images.githubusercontent.com/11466906/205990619-79eedc4f-092a-4cc2-ad2a-2e64a7254374.png)

**Comment by coleramos425** [comment]
Merged fixes. Closing ticket.
