### ISSUE TITLE
Questions about server side installation

### ISSUE THREAD

**Issue by FabioLuporini** [AMDResearch/omniperf#38]
Hello,

just a quick comment about the installation of MongoDB and Grafana via Dockerfile

One of the cool things about docker is that generally you don't need sudo. However, all the commands here prepend it to `docker`. Is there a particular reason or is it just an oversight? 

~And, related question, why aren't the MongoDB utils part of the Dockerfile?~
Ignore me, I just found out the utils are necessary to import the databases, hence they're needed locally

Thanks a lot!

**Comment by FabioLuporini** [comment]
ah, I just spotted a typo that costed me a non negligible amount of swearing 😂 

https://amdresearch.github.io/omniperf/installation.html#setup-grafana-instance

first it says port 14000 then two lines below 1400 . Correct one is 14000

**Comment by coleramos425** [comment]
Good catch, sorry about that! We've just updated the documentation so hopefully no one has to go through that again :)

**Comment by FabioLuporini** [comment]
Thanks, all good :)
