### ISSUE TITLE
Corrupted imports due to the absence of `mongoimport` should be removed or Grafana GUI won't work

### ISSUE THREAD

**Issue by FabioLuporini** [AMDResearch/omniperf#39]
Symptom: when I open a panel like "System info" or "System speed of light" the loading wheel at the top right keeps spinning forever and nothing gets displayed

**Comment by coleramos425** [comment]
Could you provide some additional information to help me troubleshoot your issue?

- Are you using your own Grafana instance or shared? 
- Have you [uploaded any workloads](https://amdresearch.github.io/omniperf/grafana_analyzer.html#grafana-gui-import) to your MongoDB backend?
- Is `http://<hostname>:27018/` reachable?
- Does **Save & Test** button described [here](https://amdresearch.github.io/omniperf/installation.html#setup-grafana-instance) indicate a successful connection?

**Comment by FabioLuporini** [comment]
* mine
* about to (see below)
* yes
* yes

I'm one step away from accomplishing the upload (had some issues yesterday because in my docker image mongoimport was still missing, so I had to tweak the Dockerfile, rebuild etc -- so I haven't tried the "full working version" yet). But: with Chrome, the loading wheel stops spinnign immediately and the tab clearly states, at the centre, "No data". With safari instead nothing gets displayed and all my clicks are like no-op. I don't know if it's an omniperf-dashboard specific issue or a more generic grafana framework issue, but somehow I thought it'd be useful to report it.

This was safari 15.2 on MacOS Monterey. Sorry about the lack of detail in the original post

**Comment by FabioLuporini** [comment]
You may close or rename, up to you: the symptom really was there, but the issue is a totally different one!

 The issue was a corrupted import via `omniperf database --import ...` -- corrupted because when I attempted it, `mongoimport` was not available yet; so the import went through, despite some warnings. I ignored that run, but I left it there. Later on, I performed more runs and imported them -- this time successfully because `mongoimport` was available. However, nothing won't show up in the GUI until I manually removed `omniperf database --remove ...` the corrupted import. Luckily I thought of that and tried it. Why Safari and Chrome would behave differently in presence of such a corrupted import I have no idea.

**Comment by coleramos425** [comment]
Okay. Thanks for sharing @FabioLuporini. While we do list `mongoimport` as a requirement in our [docs](https://amdresearch.github.io/omniperf/installation.html#install-mongodb-utils), 

![image](https://user-images.githubusercontent.com/11466906/204858399-6121a016-238c-498f-a878-39a1a73602e5.png)

we could do a better job of dependency checking here in case a user skips this step. Historically, corrupt data doesn't play nicely with the proxy server we use to forward info to our Grafana interface.
