### ISSUE TITLE
Grafana GUI documentation unclear

### ISSUE THREAD

**Issue by FabioLuporini** [AMDResearch/omniperf#41]
Documentation available at:

https://amdresearch.github.io/omniperf/grafana_analyzer.html#grafana-gui-import

Issue: to upload a database to our MongoDB server I was running

```
omniperf database --import -H <host_ip> -u admin -t asw -w workloads/devito_iso/mi200/

--------
Import Profiling Results
--------

Pulling data from  /app/workloads/devito_iso/mi200
The directory exists
Found sysinfo file
KernelName shortening enabled
Kernel name verbose level: 2
-- Conversion & Upload in Progress --
ERROR: Unable to connect to the server
```

After a short while (but still, order of minutes) I realised that `-u admin` was wrong -- because `admin` is what was used for for the Grafana service, not MongoDB. For someone like me who didn't (doesn't) know anything about Grafana and MongoDB perhaps a bit more justified to be confused...

So then I started following the docs, strictly, that is I started using `-u temp`. However I was then prompted for a password. (Much) later on, I realised the the MongoDB password was hardcoded in the Dockerfile. This could be improved I think, I think two-three more lines in the docs would be enough.

This was co-debugged with @ggorman -- just to be sure it wasn't me having an unlucky day

**Comment by coleramos425** [comment]
Thanks for sharing this feedback, Fabio. I see how these differing credentials could make things confusing.

We'll add some clarification to the docs.

**Comment by coleramos425** [comment]
The [Grafana GUI Import](https://amdresearch.github.io/omniperf/grafana_analyzer.html#grafana-gui-import) section has been updated

> Default username and password for MongoDB (to be used in database mode) are as follows:
> 
> Username: temp
> Password: temp123
