### ISSUE TITLE
Missing roofline analysis on MI300X

### ISSUE THREAD

**Issue by zjing14** [AMDResearch/omniperf#413]
**Describe the bug**
Got the following error message when running roofline analysis on MI300
`Roofline temporarily disabled in MI300`

Looks like the roofline micro-bench for MI300 is missing in `https://github.com/ROCm/omniperf/tree/amd-staging/src/utils/rooflines`

**Development Environment:**
 - Linux Distribution: [RHEL8]
 - Omniperf Version: [2.0.1]
 - GPU: [M300]

**Comment by coleramos425** [comment]
Duplicate of issue #285. Let's move the discussion there to keep things simple for tracking purposes.

**Comment by zjing14** [comment]
@coleramos425 Thanks.
