### ISSUE TITLE
Add "per-kernel" normalization mode to standalone GUI

### ISSUE THREAD

**Issue by arghdos** [AMDResearch/omniperf#42]
The 'per-kernel' normalization mode present in the Grafana dashboard appears to be missing from the standalone GUI.

This is useful for some metrics (e.g., requests, bytes moved, etc.) it's often of interest how many there were in total.
For instance, a user might want to see the _total_ number of bytes read from HBM.
Right now with the standalone GUI, the only option  is to really choose (e.g.,) per-wave and then multiply the reported value by the number of waves

**Comment by coleramos425** [comment]
This is similar enough to #30 that I'll just mention this in the comments.

Planning on rolling this out in v1.0.5
