### ISSUE TITLE
Issues with Omniperf installation

### ISSUE THREAD

**Issue by ashesh2512** [AMDResearch/omniperf#425]
Hello, I have been trying to install omniperf on our internal clusters. I was able to do so for version 1.1, and after trying to install the latest version, I run into the following error upon loading the omniperf module and trying to check the version - 

```
$ ~/opt/omniperf/6.1.2/2.0.1/bin/omniperf --version
Traceback (most recent call last):
  File "/home/users/sharmaas/opt/omniperf/6.1.2/2.0.1/bin/omniperf", line 153, in <module>
    main()
  File "/home/users/sharmaas/opt/omniperf/6.1.2/2.0.1/bin/omniperf", line 135, in main
    omniperf = Omniperf()
               ^^^^^^^^
NameError: name 'Omniperf' is not defined. Did you mean: 'omniperf'?
```

**Comment by coleramos425** [comment]
@ashesh2512 this is most likely a Python versioning mismatch. We can verify this by checking output from

- `which python3`
- `echo $PYTHONPATH`

We want to make sure you're picking up the expected Python version

**Comment by ashesh2512** [comment]
@coleramos425 

```
$ which python3
/usr/bin/python3

$ echo $PYTHONPATH
/home/users/sharmaas/opt/omniperf/6.2.0/python-libs-2.0.1
```

**Comment by ashesh2512** [comment]
FYI, I was able to make it work. This appears to be a packaging error. The script found in `$INSTALL_DIR/2.0.1/bin/omniperf` should be a symbolic link to `$INSTALL_DIR/2.0.1/libexec/omniperf/omniperf` but is its own file. Creating a symbolic link as follows is what made things work - `ln -sf $INSTALL_DIR/2.0.1/libexec/omniperf/omniperf $INSTALL_DIR/2.0.1/bin/omniperf`
