### ISSUE TITLE
How does Omniperf profile a kernel launched in multiple streams?

### ISSUE THREAD

**Issue by ashesh2512** [AMDResearch/omniperf#444]
Hello, I have a kernel that is launched across four HIP streams. When profiling with Omniperf, how are streams handled?

**Comment by coleramos425** [comment]
Copying @nartmada for triage and issue assignment

**Comment by ppanchad-amd** [comment]
@ashesh2512 @coleramos425 - Internal ticket has been created to assist with this issue. Thanks!

**Comment by sohaibnd** [comment]
Hi @ashesh2512, sorry for the delay. Currently, you can filter collection of counters by kernel name or dispatch id (see [documentation](https://rocm.docs.amd.com/projects/omniperf/en/latest/how-to/profile/mode.html#filtering)) but not by stream. In your case, if you are launching a single kernel in each stream, I believe it should be sufficient to filter by dispatch id.

**Comment by sohaibnd** [comment]
@ashesh2512 I'm going to close this issue due to inactivity. If you have any follow-up questions, feel free to re-open this issue.
