### ISSUE TITLE
Leverage container with pre-installed ROCm

### ISSUE THREAD

**Issue by koomie** [AMDResearch/omniperf#5]
A decent portion of the test CI jobs is devoted to installing ROCm each time (~10 minutes).  Consider starting from a container with ROCm pre-installed to shorten this process.  Could pull from upstream (e.g. [rocm/dev-ubuntu-22.04:latest](https://hub.docker.com/r/rocm/dev-ubuntu-22.04/tags)) or maintain our own container build.

**Comment by coleramos425** [comment]
We also have the images for roofline binaries on Docker Hub. One of which is an Ubuntu environment with ROCm 5.1.3

**Comment by koomie** [comment]
This change landed in time for v1.0.3 .release.
