### ISSUE TITLE
[Bug]: Outdated link in 'About' section

### ISSUE THREAD

**Issue by mrowan137** [AMDResearch/omniperf#500]
### Describe the bug

The link to documentation in the 'About' section is outdated:
<img src="https://github.com/user-attachments/assets/d1b404e7-3a37-4de8-9a96-a200f0e6163c" width="300" alt="rocprofiler-compute-about-section">

### Linux Distribution

N/A

### ROCm Compute Profiler Version

N/A

### GPU

N/A

### ROCm Version

N/A

### Reproducer

N/A

**Comment by dgaliffiAMD** [comment]
Thank you @mrowan137 . The link has been updated and now points to https://rocm.docs.amd.com/projects/rocprofiler-compute/en/latest/.
