### ISSUE TITLE
Is this a fundamental limitation on MI50 or completely unusable

### ISSUE THREAD

**Issue by LChangxi** [AMDResearch/omniperf#51]
Hi, I am going to use your tool to develop the analytical model tool on AMD GPU. I only have MI50 but this GPU is marked as unsupported in your document. I want to check if it is just a fundamental limitation or completely unusable. Thanks for your help.

**Comment by coleramos425** [comment]
Hi @LChangxi. MI50/Vega 20 are technically usable with Omniperf but are unsupported. You can use MI50 for experimentation, however, we do not frequently maintain its counter definitions.

Because our CI testing and development targets MI100+, we do not advertise its support.

**Comment by LChangxi** [comment]
> Hi @LChangxi. MI50/Vega 20 are technically usable with Omniperf but are unsupported. You can use MI50 for experimentation, however, we do not frequently maintain its counter definitions.
> 
> Because our CI testing and development targets MI100+, we do not advertise its support.

@coleramos425 Thanks for your information. Will try it.
