### ISSUE TITLE
Add example of SSH port forwarding to documentation

### ISSUE THREAD

**Issue by arghdos** [AMDResearch/omniperf#52]
Current documentation (https://amdresearch.github.io/omniperf/standalone_gui_analyzer.html?highlight=ssh) is a pretty good start, but lacks a worked example of:

1. How to connect to a system with a forwarded port (or at least, a link to some documentation of this)
2. How to select the forwarded port for the GUI

This would be a nice improvement, and was mentioned by some Crusher users.

**Comment by zjin-lcf** [comment]
I opened a web browser, but it refused to connect.   An example for SSH tunneling using MobaXterm is helpful. Thanks.

**Comment by coleramos425** [comment]
Thanks for the suggestion. Please expect this addition to be included in our next version early next week.
