### ISSUE TITLE
Suggestion: workload names should be checked before profiling to prevent "'-' and '.' are not permited in workload name" errors during import

### ISSUE THREAD

**Issue by ex-rzr** [AMDResearch/omniperf#58]
I created a few workloads with - in names but failed to import them to database due to:

```
Traceback (most recent call last):
  File "/home/.../omniperf/install/1.0.5/bin/omniperf", line 663, in <module>
    main()
  File "/home/.../omniperf/install/1.0.5/bin/omniperf", line 609, in main
    mongo_import(args, False)
  File "/home/.../omniperf/install/1.0.5/bin/omniperf", line 205, in mongo_import
    connectionInfo, Extractionlvl = csv_converter.parse(args, profileAndImport)
  File "/home/.../omniperf/install/1.0.5/bin/utils/csv_converter.py", line 165, in parse
    raise ValueError("'-' and '.' are not permited in workload name", db)
 ```

It would be great to have such checks before profiling.

**Comment by koomie** [comment]
Agreed - seems a check at profile execution would be beneficial here.

**Comment by koomie** [comment]
> Agreed - seems a check at profile execution would be beneficial here.

Were you able to just to rename the workload directory and then import?

**Comment by ex-rzr** [comment]
It didn't help, iirc. I guess the name is stored in one of files. I simply rerun profiling, it wasn't a big deal, just a bit inconvenient.

**Comment by koomie** [comment]
Yes, the workload name does get stored in one of the files -> `sysinfo.csv`.  You can edit this after the fact in a pinch and then proceed with the database import.  

Using the CLI analyze mode does not have the same naming restriction so I'm hesitant to disallow `-' in the workload name completely, but let us think about a way to improve here...

**Comment by coleramos425** [comment]
Thanks for the suggestion @ex-rzr. We'll verify before profiling to avoid that inconvenience in the future.

The modification has been made in `dev` and it will be rolled out in our next release.
