### ISSUE TITLE
Issue using Matplotlib with X-server

### ISSUE THREAD

**Issue by coleramos425** [AMDResearch/omniperf#62]
This seems to be an issue that only occurs when you are connected via ssh to a system that has an X-server running.

https://github.com/AMDResearch/omniperf/blob/796c495d0b41bb63f62220278bd4fdca323a463b/src/utils/plot_roofline.py#L31

The reason being that when an X-server is running, matplotlib, by default, tries to connect but can't and so he throws fatal exceptions.

### Suggested Fix
```
import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt
```

the `use('Agg')` call sets matplotlib to use the non-interactive backend that can only write to files. This is apparently required if you happen to run omniperf on a system with X running.

CC: @keithloweryamd

**Comment by jrmadsen** [comment]
```python
import os

# allow the user to override the default matplotlib backend
# other non-interactive options: cairo, pdf, pgf, ps, svg, template
os.environ.setdefault("MPLBACKEND", "agg")

import matplotlib

try:
    import matplotlib.pyplot as plt
except ImportError:
    matplotlib.use("agg", force=True)
    import matplotlib.pyplot as plt

**Comment by coleramos425** [comment]
Thanks for the suggestion @jrmadsen. Added this to dev branch.
