### ISSUE TITLE
Update minimum version requirements for rocm

### ISSUE THREAD

**Issue by koomie** [AMDResearch/omniperf#64]
With the switch to leverage counter files supplied directly with rocm, it appears the minimum version check may need to be updated. Running on Crusher, I get an unknown hardware counter in profile mode using rocm/5.1.0. Howevere, rocm/5.2.0 runs without incident.

In the meantime, I have updated the minimum version requirement for the omniperf/1.6.0 module on Crusher to require rocm 5.2.0 or newer.

**Comment by coleramos425** [comment]
Done.
