### ISSUE TITLE
PMC metric not found

### ISSUE THREAD

**Issue by aosewski** [AMDResearch/omniperf#75]
Hi,

I'm trying to profile a program on MI100 GPU and got following error:
```
ERROR: rocprofiler_open(), Initialize(), input metric 'TCP_GATE_EN1_sum' is not found
```
Similarly the metric `SQ_IFETCH` is also not found. 
I'm using ROCm 5.3.0 and I can't find those metrics for MI100 in rocprofile https://github.com/ROCm-Developer-Tools/rocprofiler/blob/rocm-5.3.0/test/tool/gfx_metrics.xml#L80

I'm using version 1.0.6.

[EDIT]
I see that such _expressions_ are defined here: https://github.com/ROCm-Developer-Tools/rocprofiler/blob/amd-master/test/tool/metrics.xml#L127 However this one and a lot of others are defined only for MI200. And you are using them for MI100: https://github.com/AMDResearch/omniperf/blob/main/src/perfmon_pub/mi100/pmc_tcp_perf.txt

**Comment by coleramos425** [comment]
Thank you for reporting this discrepancy @aosewski. It's possible there are some counters that may have slipped into MI100 configs we overlooked.

Let me cross-check our listings and I'll report my findings in this thread.

**Comment by coleramos425** [comment]
Update: I've confirmed this issue on ROCm 5.3.x and 5.4.x releases. Looking into possible solutions to include in our v1.0.7 release

**Comment by coleramos425** [comment]
Fix has been merged into `dev` branch. Closing issue.
