### ISSUE TITLE
Installation issue

### ISSUE THREAD

**Issue by rajaroracmu** [AMDResearch/omniperf#79]
Hi, I tried to install omniperf version 1.0.6 by following the steps listed in the documentation. 
When I use the tar version (download from releases), I get this error

```
CMake Error at cmake_install.cmake:66 (file):
  file INSTALL cannot find
  "/home/rajarora/tools/omniperf/omniperf-1.0.6/VERSION.sha": No such file or
  directory.
```

However, when I use the repository, the installation is successful. 
Please let me know if more information is needed.

Thanks.

**Comment by coleramos425** [comment]
Please try again downloading omniperf-v1.0.7.tar.gz [here](https://github.com/AMDResearch/omniperf/releases). I can confirm VERSION.sha is included.

**Comment by koomie** [comment]
Apologies I missed this - just an additional comment that you want to start from our "release" tarball asset, not the tarball that is auto-generated by github.  We try to call out the correct link in the release notes, but  in general, you want to start from the file named "omniperf-v{xx}.tar.gz".

@coleramos425 provided the latest link above. For the v1.0.6 release you mentioned, the correct tarball is:

https://github.com/AMDResearch/omniperf/releases/download/v1.0.6/omniperf-v1.0.6.tar.gz

That should include the missing VERSION.sha file you noted.
