### ISSUE TITLE
Wavefront launch stats also only normalized by waves

### ISSUE THREAD

**Issue by arghdos** [AMDResearch/omniperf#81]
Similar to https://github.com/AMDResearch/omniperf/issues/68, these values are only normalizable by waves:

https://github.com/AMDResearch/omniperf/blob/main/src/omniperf_analyze/configs/gfx90a/0700_wavefront-launch.yaml#L101

It would be a good idea to check all the YAML files to get this once and for all

**Comment by coleramos425** [comment]
Enabled multi-normalization for

- Wave Cycles
- Dependency Wait Cycles
- Issue Wait Cycles
- Active Cycles

Others like "Kernel Time (Nanosec)", "Kernel Time (Cycles)", "Instr/wavefront" did not change because their name explicitly defines a static normalization.
