### ISSUE TITLE
Omniperf version without --gui support? 

### ISSUE THREAD

**Issue by gmarkomanolis** [AMDResearch/omniperf#82]
We would like to have an Omniperf release without --GUI functionality, so the workflow would be for the users to download the data to their personal computers and they run from there the Omniperf with --gui support.

**Comment by coleramos425** [comment]
We can create a branch that meets these requirements from which you can tar and distribute. Would this be satisfactory?

**Comment by gmarkomanolis** [comment]
Sure, something public though right? We would like this version to be upgraded when it is required.

**Comment by coleramos425** [comment]
Yes

**Comment by coleramos425** [comment]
Done. 
`git fetch --prune && git checkout no-gui`
