### ISSUE TITLE
Kernel ID listing not consistent

### ISSUE THREAD

**Issue by ooreilly** [AMDResearch/omniperf#83]
How are the kernel IDs ordered when using:
```
omniperf analyze --list-kernels ...
```
? 
It appears that the order can change when profiling the same application. It would be good to be able to sort the kernels by name such that a consistent ordering of kernels can be guaranteed.

**Comment by coleramos425** [comment]
At the moment `--list-kernels` will output the top 10 kernels (by duration) in the application. This may change from profile to profile because of a difference in runs?

Regardless we should make this clear in `--help` menu. I'll add this detail to the option description.

**Comment by coleramos425** [comment]
Since the CLI uses `-k <id>` or id based kernel filtering and `--list-metrics` only lists Top 10 kernels it raises the question
> How do I filter by name in the analysis stage? 

And at the moment if using CLI you only have the ability to filter a kernel if it exists in the Top 10. This is a limitation of the CLU interface that should be addressed.

@feizheng10 I'm interested to hear if you have any ideas.

**Comment by feizheng10** [comment]
For --list-kernels, I believe we sort the kernels by name here https://github.com/AMDResearch/omniperf/blob/79762b18cee03a45b3aa01d96fffab8805c426ac/src/omniperf_analyze/utils/tty.py#L191 

To match it, it seems to me we could change https://github.com/AMDResearch/omniperf/blob/79762b18cee03a45b3aa01d96fffab8805c426ac/src/omniperf_analyze/utils/file_io.py#L113
default to KernelName.

Still, we should discuss the proper strategy later.

**Comment by coleramos425** [comment]
Issue is temporarily fixed through #123. Please see PR for full details, but users can now use `--max-kernel-num` to change default number of kernels displayed in CLI "Top Stats" table
