### ISSUE TITLE
Error while comparing two workloads

### ISSUE THREAD

**Issue by aosewski** [AMDResearch/omniperf#86]
I'm using Omniperf v1.0.6.

When I try to compare two kernels from different workloads I get ie. such error:
```
Failed to upgrade legacy queries Datasource oVK0I__nk was not found
```
My panel "System Speed of Light" cannot display correctly since:

```
Cannot read properties of null (reading '0')
Object
status:500
statusText:"Internal Server Error"
data:Object
message:"Cannot read properties of null (reading '0')"
config:Object
url:"api/datasources/proxy/1/query"
data:Object
method:"POST"
withCredentials:undefined
headers:Object
retry:0
hideFromInspector:false
message:"Cannot read properties of null (reading '0')"
```
By the way when opening any workload in Grafana I get a bunch of error pop-up messeges.

**Comment by aosewski** [comment]
Which version of Omniperf would you recommend to use, since I see that v1.0.6 is unstable...

**Comment by coleramos425** [comment]
Some further information will be required to answer this. I will contact you internally and share an update in this thread.

**Comment by coleramos425** [comment]
I was able to get @aosewski up and running on [Omniperf_v1.0.3_pub.json](https://github.com/AMDResearch/omniperf/blob/main/dashboards/Omniperf_v1.0.3_pub.json) w/o issue. For some reason, one of his workloads has some backwards compatibility issues on [Omniperf_v1.0.5_pub.json](https://github.com/AMDResearch/omniperf/blob/main/dashboards/Omniperf_v1.0.5_pub.json) causing the error above.

Going to get a copy of this particular workload to test things out on my end.

**Comment by coleramos425** [comment]
Hi Adam. Please reach out if you are still facing issues with this since our last discussion. Thanks!
