### ISSUE TITLE
Create one roofline plot per kernel

### ISSUE THREAD

**Issue by gmarkomanolis** [AMDResearch/omniperf#93]
When we execute omniperf with could we have except a roofline plot with all the kernels and one plot per kernel? When we have the plot with all the kernels, we do not know the names. Just to add motivation to my request, imagine we have blocked the --gui and there is no grafana and we would like to see rooflines for the top 10 kernels, so we can have 10 PDFs, name the PDF the kernel name or whatever you prefer and we can see the roofline of each kernel. At least this will help a bit until the other issue gets fixed with the roofline and filtering the kernels.

**Comment by coleramos425** [comment]
@gmarkomanolis I can understand the use case you are describing, but generating 10 plots (x2 for each dtype) seems a bit excessive.

Perhaps an optional like `--kernel-names` could change each AI point in the graph to a different shape. Then a legend could be provided to identify each kernel based on its shape. Here only one graph would be needed...
![image](https://user-images.githubusercontent.com/11466906/221005066-a798d250-5a10-4781-8bfb-c1fbee70214c.png)

**Comment by gmarkomanolis** [comment]
If it is easy to map the kernel name to the data point while reading the plot, it is ok.

**Comment by coleramos425** [comment]
See [Omniperf/kernel-names](https://github.com/AMDResearch/omniperf/tree/kernel-names) branch for initial implementation.

You can now run Omniperf with `--kernel-names` to activate this functionality. i.e.
```console
$ omniperf profile -n dummy --roof-only --kernel-names -- <app_cmd>
```
